### ISSUE TITLE
GNSSRO test failing in develop

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA/ioda-converters#234] opened 2019-11-15 23:49 UTC
Just reporting that test_iodaconv_gnssro_bufr_conv fails in develop. @hailingz , I assigned you, since it seems you wrote the converter, but feel free to ignore or assign somebody else obviously.

**Comment by srherbener** [comment] 2019-11-16 00:41
@guillaumevernieres, thanks for the report. @hailingz wrote the converter, but @markjolah did the CMake configuration for the build and test. I replaced Hailing with myself and Mark for this issue.

The CMake configuration will only build and test if the netcdf and bufrlib libraries are found, so I assume that those exist in your environment.

I thought this was working in the containers and on Hera and Discover. It just tried it on my iMac and the test passed. Could you send more details about the failure. What machine/environment are you using? Also could you cut and paste the failure message in a comment for this issue? 

Thanks!

**Comment by guillaumevernieres** [comment] 2019-11-16 12:26
@srherbener : Have a look at the [travis-ci output](https://travis-ci.com/JCSDA/ioda-converters/builds/136791287) from PR #232, it fails in the singularity container as well. 
It looks like the converter was not built (executable not in the bin directory), but the test is being run, that's what I see in the container, I presume this is the same issue on travis-ci.

**Comment by srherbener** [comment] 2019-11-18 16:35
@guillaumevernieres, I just tried running in CharliCloud on my iMac. The build/test works okay for the default build mode (--build=RelWithDebInfo), but get the same failures as Travis-CI in debug build mode (--build=Debug). The issue is that in debug build mode the netcdf fortran library (libnetcdff.so) does not get included in the link command for the GNSSRO fortran converter program. This is the same failure that Travis-CI is experiencing.

I'll continue to debug this, and hopefully find a fix soon.

**Comment by srherbener** [comment] 2019-11-18 17:22
@guillaumevernieres, I can get this to work by using ecbuild 3.1.0 in my CharlieCloud container. (The containers are using ecbuild 2.9.4). I'm not sure about all of the ramifications of installing ecbuild 3.10 in the container, but that would be the ideal solution. I'll ask @mmiesch about this.

**Comment by srherbener** [comment] 2019-11-18 19:07
I found a workaround that is compatible with ecbuild 2.9.4 and 3.1.0, and I have committed that workaround to the cryosat PR (#232). If this passes the Travis-CI test, then I think we are good to go.

**Comment by markjolah** [comment] 2019-11-18 19:26
This is a bug with ecbuild `FindNetCDF4.cmake`.  It produces an invalid `NETCDF_LIBRARIES`  CMake variable.  The correct place will be to address will be in ecbuild.  I can look into this later this week.  For now we can use @srherbener's patch.

**Comment by srherbener** [comment] 2019-11-18 19:31
@markjolah, no need to debug, the FindNetCDF.cmake script in ecbuild 3.1.0 returns a valid NETCDF_LIBRARIES variable so the problem has already been addressed. Once we move all stacks (HPC, containers, etc) to ecbuild 3.1.0 we can get rid of my patch.

**Comment by mmiesch** [comment] 2019-11-18 20:02
As far as I know, all containers (gnu, intel 17, intel 19) should be up to date with ecbuild 3.1.0 or later (ecbuild/ecmwf-develop).  If this is not the case let me know.  I think the new clang container is still using jcsda-release-stable so I need to update that but the others should be good.  And, all environment modules on Cheyenne, S4, Discover, and AWS should be using ecbuild 3.1.0 or ecmwf-develop.   So, as far as I know, everything is already updated to ecbuild 3.1.0.

**Comment by srherbener** [comment] 2019-11-18 20:34
@mmiesch, on my iMac I tried this copy of CharlieCloud `wget http://data.jcsda.org/containers/ch-jedi-latest.tar.gz` and when I ask ecbuild for its version, I get this:
```
vagrant@vagrant:~$ ecbuild --version
ecbuild version 2.9.4
set( ECBUILD_MACRO_VERSION "${ECBUILD_VERSION_STR}" )
cmake version 3.13.0
```

Tried Sinugularity as well:
```
vagrant@vagrant:~$ singularity pull shub://JCSDA/singularity
INFO:    Downloading shub image
 957.13 MiB / 957.13 MiB [=====================================================================] 100.00% 51.31 MiB/s 18s

vagrant@vagrant:~$ singularity shell -e singularity_latest.sif

Singularity singularity_latest.sif:~> ecbuild --version
ecbuild version 2.9.4
set( ECBUILD_MACRO_VERSION "${ECBUILD_VERSION_STR}" )
cmake version 3.13.0
```

Perhaps, I'm downloading the images from the wrong repositories?

**Comment by mmiesch** [comment] 2019-11-18 21:22
Ok - I updated the intel containers - I'll check gnu.  I'm occupied with SC19 today but I'll get to it by tomorrow.

**Comment by markjolah** [comment] 2019-11-18 21:23
I am getting success with jcsda/docker-gnu-openmpi-dev which has ecbuild 3.1.0.  It seems the older jcsda/docker was not updated with the newer ecbuild.  Is this older container deprecated now that we have gnu and intel containers?  It seems @srherbener is using Signularity and CC containers that are based off of the jcsda/docker images as it has the same version of ecbuild.

**Comment by mmiesch** [comment] 2019-11-18 22:18
Yes - let me fix this tomorrow - maybe tonight - it has to do with name changes when the number of containers went from one (gnu-openmpi) to four.  It's just bookkeeping - I'll keep you posted.

**Comment by srherbener** [comment] 2019-11-18 22:26
@mmiesch, thank you for helping with this! No need to rush. It would be fine to wait until tomorrow to start.

**Comment by mmiesch** [comment] 2019-11-19 03:38
Ok - the Charliecloud and singularity containers should be up to date with ecbuild develop (3.1.0 plus the URL capability that @mer-a-o wants to use for testing).  Also, the clang container has been updated - there's a docker version on docker hub and a charliecloud version here:
~~~~~
wget https://data.jcsda.org/containers/ch-clang-mpich-dev.tar.gz
~~~~~
I still need to update the docs and web page.

**Closed** 2019-12-04 23:38 UTC
Labels: bug
