### ISSUE TITLE
test_iodaconv_smap_sss now failing on Theia

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA/ioda-converters#191] opened 2019-06-21 16:15 UTC
I'm not sure who wrote the smap_sss test/converter but somehow now it's failing in the tests for ioda-converters (at least on Theia) both in develop and my pending PR branch (both @louiskouvaris  and I noticed this). Can someone (@srherbener perhaps) confirm that it still passes for them and I can try to figure out why it's now failing on this machine.

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 16:41
Somehow the output timestamps are now different for all but 1 of the locations. And the test output has many repeating times that are not in the reference file. I wonder if this is somehow related to the computation of time = reference_time + seconds_since_ref_time ? Seems odd that it would just now start, so it must either be related to a change in Python software / environment or some quirk of the Unix epoch (most likely the former)

**Comment by srherbener** [comment] 2019-06-21 17:06
@CoryMartin-NOAA, the test_iodaconv_smap_sss test is passing on my iMac both inside (CharlieCloud) and outside the containers.

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 17:09
@srherbener thanks for checking, I assumed that would be the case. I don't know why it's failing now on Theia. I won't worry about it for the short term, just putting it on here so others are aware that it may fail because of mismatched timestamps.

**Comment by srherbener** [comment] 2019-06-21 17:15
@CoryMartin-NOAA, I take that back. I thought I was in a window running (vagrant/charlicloud) but was not. The test passes outside containers, but fails in CharlieCloud on my iMac. I'm seeing timestamp differences like you described. I hadn't been using the containers much lately, but it looks like something has sneaked in recently.

I wonder if the SMAP SST test is not using ordered dictionaries? Could this be just a re-ordering of the output?

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 17:18
@srherbener no I don't think so. I notice a lot of the same value for time@MetaData (-10.1689). This also is not in a container, but natively on Theia with 'module load jedi' and 'module load anaconda/anaconda3-5.3.1' It's only in the reference file once but it's the time value for almost all of the positions. This seems really strange to me.

**Comment by srherbener** [comment] 2019-06-21 17:24
@CoryMartin-NOAA, I just started looking at the differences, and I agree. I'm seeing the repeated values too (-10.16889). I suspect that we might be seeing the same results, so it may be repeatable but I'm not sure what's wrong.

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 17:29
@HamidehGMAO any ideas? I think I found that you were the original author of this converter?

**Comment by HamidehGMAO** [comment] 2019-06-21 17:38
hmm, I'm in the middle of something right now, I can take a look in a couple of hours, But, I remember one of the Steve's subroutines ( I guess ncwrite) was just running with python 2.7 but not higher versions, it might be related to that!?


________________________________

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 17:49
@HamidehGMAO no rush. It could be since I am using Python 3 but the weird thing is it has worked previously with the exact same version of Python and now it's not.

**Comment by srherbener** [comment] 2019-06-21 18:13
@CoryMartin-NOAA and @HamidehGMAO, I started looking into this and the issue seems to be single vs double precision floating point values for the time variable (which is in seconds since a reference time). I'm just printing out variable values on the working version (outside the container) and comparing to the same on the broken version (inside the container). The working version appears to be double precision, the broken version appears to be single precision, and the reference time (Jan 1, 2000) is far enough away that this difference matters. The single precision is truncating the values and that's why the -10.16889 is repeated many times.

I'm not sure what is causing the change in precision yet.

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 18:31
@srherbener is there a difference in the version of numpy (or even the C compiler that Numpy was made with)? Perhaps that is the issue. But again the weird thing is that it used to work and now it doesn't, so why would the precision change (and across multiple platforms). Unless it has to do with seconds since the reference time referring to the system time?

**Comment by srherbener** [comment] 2019-06-21 19:00
@CoryMartin-NOAA, where it works numpy is 1.16.4, where it fails numpy is 1.11.0.

This is definitely being a pain - it looks like the netcdf interface itself is changing the precision to single precision. The netcdf interface reports the variable as double, but returns truncated values! Not sure why it's doing this. The python netcdf4 libraries are different versions: working one is 1.4.2, the failing one is 1.5.1.2. However, I'm pretty these versions haven't changed since before the problem showed up.

**Comment by srherbener** [comment] 2019-06-21 19:43
@CoryMartin-NOAA and @HamidehGMAO, I got it fixed. The issue was that the input netcdf file is built incorrectly. The 'time' variable is double precision (has to be since it's seconds from Jan 1, 2000) but it's attributes 'scale_factor' and 'add_offset' are single precision. Changing these attributes to double precision fixed the problem (at least in my container, but I'm guessing this will fix Theia as well).

If a netcdf variable has attributes add_offset and scale_factor, they are automatically applied to linearly translate the variable values: new value = old value * scale_factor + add_offset. The mix of single and double precision values causes automatic conversion, so in some cases convert the single to double and in other cases convert the double to single. Not sure why this isn't consistent across platforms.

I'll submit a PR now.

**Comment by CoryMartin-NOAA** [comment] 2019-06-21 19:45
@srherbener huh, fascinating. Good to know and great that you figured it out already!

**Comment by guillaumevernieres** [comment] 2019-06-21 21:10
Sorry for reopening this but I disagree with the current fix. ctest are there to detect problems, the PR associated with this issue only fixes the ctest, not the problem! 
We can certainly ask RSS to fix their files, but this is going to take weeks/months/years, if ever. Can we unmerged the last PR? Sorry for being picky, but this is going to be a problem not too far down the road.

**Comment by HamidehGMAO** [comment] 2019-06-21 21:14
Yeah, You are right.

**Comment by srherbener** [comment] 2019-06-21 21:16
No problem. I'll revert the PR.

However the only alternative I can think of is to modify the netcdf interface supplied by Unidata, which I think suffers the same issue - it could be weeks/months/years if ever for the fix appears.

We cannot do anything about this in our scripts.

**Comment by srherbener** [comment] 2019-06-21 21:19
Okay, the PR has been reverted.

**Comment by srherbener** [comment] 2019-06-21 21:39
My argument is that the problem is the file and as such the file needs to be fixed. However, I do understand the potential difficulty of getting the supplier (RSS ?) to change their process.

Here is what I did to modify the input file. This changes the attributes (scale_factor and add_offset) to double precision with the same values they had before.
~~~~~~~~
ncatted -O -a scale_factor,time,m,d,1.0 smap_sss_rss.nc
ncatted -O -a add_offset,time,m,d,0.0 smap_sss_rss.nc
~~~~~~~~

We could put this in as a step when we pull files from RSS, but it will be problematic trying to automatically track where we need to do this step and to set the attribute values correctly, etc.

**Comment by srherbener** [comment] 2019-06-21 21:53
Hi @guillaumevernieres, Let's track all the discussions in this github issue so can keep them all in one place. Here is your comment from the revert PR:

Thanks @srherbener, sorry for being picky, but that's a point of failure outside of ctest. @CoryMartin-NOAA , was it failing on Theia? It works on the container, which could also indicate that the netcdf module we use might not apply the scaling/offset byt default (?). We've had that issue in the past.
I realized I'm late to the discussion, sorry again!

**Comment by guillaumevernieres** [comment] 2019-06-21 21:54
I'll have a look at the reading part, not all netcdf module apply the
offset/scaling. I could also just apply  your 2 ncatted lines in our obs
scripts (in soca), that might be the easier solution.

**Comment by srherbener** [comment] 2019-06-21 22:25
No problem about reverting the PR. Sorry I missed your feedback before I merged in the PR.

The SMAP SSS test passes outside the containers on my iMac. The test fails on Theia and inside CharlieCloud on my iMac. I'm assuming that this means that it would also fail in Singularity.

In this particular case, the time values are double precision and scale =1 and offset = 0 (ie, no translation) so if the scale and offset were not applied you would get double precision time values and the test would pass. I actually tried this first by deleting the offset and scale attributes and it did work, but I thought it would be better to not delete these attributes.

I agree that putting the ncatted lines in the SOCA obs scripts is a way to get a fix in easily, but I am concerned that having us repair files we receive from data centers could be problematic for a long term solution. Besides, the people at the data centers would probably want to know that they are shipping files containing inconsistencies such as this case.

**Comment by guillaumevernieres** [comment] 2019-06-21 22:33
@srherbener : I agree.
Eric, who works at the GMAO is in contact with the SMAP science team (I think). @HamidehGMAO , could you have a chat with Eric and ask him who we should contact to have the problem fixed?
In the meantime I'll add your 2 nco lines to our script in soca. 
It works on singularity for me, but my image is probably outdated.

**Comment by HamidehGMAO** [comment] 2019-06-21 22:58
Sure! I will talk with Eric next week
________________________________

**Comment by srherbener** [comment] 2019-06-21 23:01
@guillaumevernieres, this sounds great, thanks. And thanks @HamidehGMAO for helping to get the files fixed at the data center.

**Comment by guillaumevernieres** [comment] 2019-06-21 23:11
:+1:  So I guess you can revert^2 :)
We have an issue in soca to remind us to actually implement a fix! So we're all good with the merge of your previous pr.
Thanks for finding/fixing the issue.

**Comment by srherbener** [comment] 2019-06-21 23:13
Sounds good, I'll revert the revert :)

**Closed** 2019-06-25 15:57 UTC
